server {
    listen 80;
    server_name mrshedar.tech;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name mrshedar.tech;
    
    ssl_certificate /etc/letsencrypt/live/mrshedar.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mrshedar.tech/privkey.pem;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
